### ISSUE TITLE
Remove "main" from bower file

### ISSUE THREAD

**Issue by bartvde** [highsource/w3c-schemas#11]
We should probably remove:

```
"main": "scripts/w3c-schemas.js",
```

from the bower config file.

**Comment by highsource** [comment]
Duplicate for #12.

**Comment by highsource** [comment]
@bartvde @juanmav 
So far I've came up with the following AMD and CJS-compatible module:

https://github.com/highsource/w3c-schemas/blob/master/scripts/w3c-schemas.js

Which is ugly as hell.

**Comment by highsource** [comment]
I've reverted changes to `w3c-schemas.js` and added individual scripts to `main` instead:

```
  	"main": [
		"scripts/lib/Atom_1_0",
		"scripts/lib/WS_Addr_1_0_Core",
		"scripts/lib/XHTML_1_0_Strict",
		"scripts/lib/XLink_1_0",
		"scripts/lib/XSD_1_0"
	]
```
